
# Site settings
title: Διακομόπουλος Γιάννης &bull; Αγγλικά &bull; Γερμανικά &bull; Χαλκίδα
email: info@diacomopoulos.gr
description: > # this means to ignore newlines until "baseurl:"
  Διακομόπουλος Γιάννης - Αγγλικά - Γερμανικά - Χαλκίδα

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.diacomopoulos.gr/" # the base hostname & protocol for your site
permalink: /blog/:title

twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
